FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8 as runner

WORKDIR /convbot-fatapi

RUN python3 -m pip install poetry && poetry config virtualenvs.create false

COPY . .

RUN poetry install --no-root --no-dev

EXPOSE 8000

CMD python3 -m convbot_fastapi
